### ISSUE TITLE
Markbot is saying "The element, body > header doesn't exist on the page.

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/kraken-good-accessibility#1]
@HannahDelaney @hellachella

Do you know what this means? I clearly have my <header> tag under my body, so I'm not too sure as to what the issue is.

<img width="510" alt="Screen Shot 2020-09-28 at 9 34 07 AM" src="https://user-images.githubusercontent.com/54897840/94438951-c601c580-016d-11eb-85c3-88314b3f8ed4.png">

**Comment by HannahDelaney** [comment]
So I think Markbot just wants the `header` tag _directly_ under the `body` tag. There are actually two `header` tags in this assignment, so while you do have one, it's not the specific one Markbot is looking for.

If you change the `article` tag that is the direct child of the `body` to a `header`, it should solve your issue. It's coming up as a "contrast" issue because of the css that is applied to the `header` tag that makes the content more visible. Once you change that `article` to be a `header` suddenly your site will look rather fabulous ;)

**Comment by Sophia-Villamayor** [comment]
Thank you!!
