### ISSUE TITLE
My icons within my navigation aren't lining up with the h2

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/kraken-good-accessibility#2]
@HannahDelaney @hellachella

It seems that the icons in my nav aren't flowing in one line with the h2. A
<img width="599" alt="Screen Shot 2020-09-28 at 10 28 29 AM" src="https://user-images.githubusercontent.com/54897840/94445703-c00fe280-0175-11eb-988b-4a57991f1a11.png">
ny suggestions? :(

**Comment by HannahDelaney** [comment]
This one is a bit tricky because the CSS is established already. There are a couple of semantic differences that will align your code with the CSS that is written.

The main one is that there is an `<article>` tag missing from your content that is a parent for a lot of the styling added. The article wraps around almost all of the content, opening above the second `<header>` tag starts and closing before the second `<footer>`. As it's a literary piece, it would likely be considered an "article" like in a magazine, even in an online context.

That should fix your nav alignment. It will likely cause your text to disappear, because there is now a `#fff` text colour being applied. You'll have to go find out why in your CSS to fix that new issue ;)

**Comment by hellachella** [comment]
Your navigation needs to be inside the `header` rather than have two.

You don't need to section out the header. Use `hgroup` for your `h1` and `h2`

```
      <hgroup>
        <h1>Chapter XVIII</h1>
        <h2>The Poulps</h2>
      </hgroup>
```

```
    <header>

      <hgroup>
        <h1>Chapter XVIII</h1>
        <h2>The Poulps</h2>
      </hgroup>

      <nav role="Assign appropriate landmark role here">
        <ul>
          <li></li>
          <li></li>
          <li></li>
        </ul>
      </nav>

    </header>
```
